"""add expense review workflow (status, submitted_by, reviewed_by, reviewed_at), expand expense types

Revision ID: ae16247f30b9
Revises: 07980265b035
Create Date: 2026-07-13 15:11:46.066364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae16247f30b9'
down_revision: Union[str, None] = '07980265b035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: explicitly create
    # the Postgres enum type first (autogenerate doesn't always emit this),
    # and give status a server_default so this works even if the expenses
    # table already has rows.
    expense_status_enum = sa.Enum('Pending', 'Approved', 'Rejected', name='expensestatus')
    expense_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'expenses',
        sa.Column('status', expense_status_enum, nullable=False, server_default='Pending'),
    )
    op.add_column('expenses', sa.Column('submitted_by', sa.String(length=36), nullable=True))
    op.add_column('expenses', sa.Column('reviewed_by', sa.String(length=36), nullable=True))
    op.add_column('expenses', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['submitted_by'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'reviewed_at')
    op.drop_column('expenses', 'reviewed_by')
    op.drop_column('expenses', 'submitted_by')
    op.drop_column('expenses', 'status')
    sa.Enum(name='expensestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
